worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;

    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;

        # API routing
        location /api/patients {
            proxy_pass http://patient_service:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/doctors {
            proxy_pass http://doctor_service:8002;
            proxy_set_header Host $host;
        }

        location /api/appointments {
            proxy_pass http://appointment_service:8003;
            proxy_set_header Host $host;
        }

        location /api/auth {
            proxy_pass http://appointment_service:8003;
            proxy_set_header Host $host;
        }

        location /api/emr {
            proxy_pass http://emr_service:8004;
            proxy_set_header Host $host;
        }

        location /api/pharmacy {
            proxy_pass http://pharmacy_service:8005;
            proxy_set_header Host $host;
        }

        location /api/billing {
            proxy_pass http://billing_service:8006;
            proxy_set_header Host $host;
        }
    }
}
